module.exports = [
	{ path : '/', method : 'home' },
	{ path : /-lb$/, method : 'lightbox' },
	{ path : /-lb2$/, method : 'lightbox2' },
	{ path : /\.htm$/, method : 'content' },
	{ path : '/customer-service', method : 'customerService' },
	{ path : '/customer-service', method : 'postCustomerService', verb : 'post' },
	{ path : '/share-sili', method : 'shareSili' },
	{ path : '/share-sili', method : 'postSiliShare', verb : 'post' },
	{ path : '/about-silipint', method : 'landing' },
	{ path : '/about-silicone', method : 'landing' },
	{ path : '/account', method : 'account' },
	{ path : '/sign-in', method : 'signin' },
	{ path : '/sign-out', method : 'signout' },
	{ path : '/forgot-password', method : 'forgotPassword' },
	{ path : '/subscribe', method : 'subscribe', verb : 'post' },
	{ path : '/artist-series', method : 'collection' },
	{ path : '/cart', method : 'cart' },
	{ path : '/checkout', method : 'checkout' },
	{ path : '/colored-drinking-glasses', method : 'collection' },
	{ path : '/contact-us', method : 'contactus' },
	{ path : '/customize', method : 'landing' },
	{ path : '/customize/:page', method : 'listing' },
	{ path : '/faq', method : 'faq' },
	{ path : '/find-a-retailer', method : 'findaretailer' },
	{ path : '/gift-cards', method : 'collection' },
	{ path : '/half-pint-glasses', method : 'collection' },
	{ path : '/lids', method : 'collection' },
	{ path : '/new-silipint-products', method : 'collection' },
	{ path : '/personalize-a-pint-glass', method : 'content' },
	{ path : '/pint-glasses', method : 'collection' },
	{ path : '/sale', method : 'collection' },
	{ path : '/sales', method : 'collection' },
	{ path : '/sell-silipint', method : 'content' },
	{ path : '/shop-silipint-drinking-glasses', method : 'shop' },
	{ path : '/shorty-cups', method : 'collection' },
	{ path : '/shot-glasses', method : 'collection' },
	{ path : '/sili-life', method : 'landing' },
	{ path : '/sili-life/:page', method : 'listing' },
	{ path : '/sili-life/artists-series', method : 'collection' },
	{ path : '/sili-life/news', method : 'collection' },
	{ path : '/sili-life/videos', method : 'collection' },
	{ path : '/silipint-sets', method : 'collection' },
	{ path : '/wine-bottle-stopper', method : 'collection' },
	{ path : '/refresh', method : 'refresh' },
	{ path : /(oz|-detail)$/, method : 'detail' },
];
